### ISSUE TITLE
Choose a less crappy name

### ISSUE THREAD

**Issue by mrkline** [mrkline/promptoglyph#5]
As [some](http://www.reddit.com/r/programming/comments/2ygkal/introducing_promptd_a_few_small_tools_for_your/cp9usuw) have pointed out, "promptd" sounds like a daemon.

dprompt?
prompted?

**Comment by mrkline** [comment]
I'm currently thinking of going with "promptoglyph". Cheesy, yes, but
1. It doesn't sound like a daemon name.
2. A google search shows zero hits, so it's unique.

**Comment by dgollub** [comment]
How about **dvcs-prompt**? A bit of a play on words that you use **D** to program it and **DVCS** itself stands for `Distributed Version Control System`. A quick Google search reveals no related tools.

Up to you. I would be okay with "promptoglyph" as well.

**Comment by mrkline** [comment]
I'm leaning towards "promptoglyph" only because I plan on supporting Subversion and other more traditional VCSes, so I don't want to give the impression that it only works with Git, Mercurial, Bazaar, and the like. Also, promptoglyph seems a bit more indicative of what it does, so that its purpose isn't confused with something like [gitsh](https://github.com/thoughtbot/gitsh).
